-- CreateTable
CREATE TABLE `MaxicareMasterlist` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clientId` INTEGER NOT NULL,
    `PY` VARCHAR(191) NULL,
    `ACCOUNT_NO` VARCHAR(191) NULL,
    `STATUS` CHAR(1) NULL,
    `MEMBER_TYPE` CHAR(1) NULL,
    `LIMIT` DOUBLE NULL,
    `RELATION` VARCHAR(191) NULL,
    `EE_ID` VARCHAR(191) NULL,
    `CARD_NO` VARCHAR(191) NULL,
    `COMPANY` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MaxicareMasterlist` ADD CONSTRAINT `MaxicareMasterlist_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `Clients`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
